[project]
name = "Vosk-Speech-To-Text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "sounddevice>=0.5.1",
    "vosk>=0.3.45",
]